### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mattwelborn** [Laboratoire-de-Chemoinformatique/SynthI#1]
Based on the README, it seems this repository is meant to be open-source. However, it is not open-source until a license is added. Please add a(n open-source) license if you do intend for this code to be open-source.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by YulianaZabolotna** [comment]
Thank you for the feedback, the license has been added.

**Comment by mattwelborn** [comment]
Thank you!
