### ISSUE TITLE
how to get outENSynthmode.smi?

### ISSUE THREAD

**Issue by 007xjx** [Laboratoire-de-Chemoinformatique/SynthI#8]
how to get the outENSynthmode.smi for "SyntOn-Enumeration"? what's the format of content in this file?

**Comment by YulianaZabolotna** [comment]
outENSynthmode.smi is a library of synthons that you want to use for enumeration. It is generated from avaialable BBs using SyntOn_BBsBulkClassificationAndSynthonization.py, it will be written in the required format, so once you synthonize your BBs library you can move on with the enumeration, no other preprocessing is needed. 

More details including the example of this out file (outSuffixName_Synthmode.smi) you can find here - https://github.com/Laboratoire-de-Chemoinformatique/Synt-On#bulk-synthons-generation-for-the-large-bbs-library.
